from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any


def load_yaml_config(path: Path) -> dict[str, Any]:
    try:
        import yaml
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError("Instale PyYAML com: pip install pyyaml") from exc

    return yaml.safe_load(path.read_text(encoding="utf-8"))


def quote_block(value: str) -> str:
    escaped = value.replace('"""', '\\"\\"\\"').strip()
    return f'"""\n{escaped}\n"""'


def render_modelfile(config: dict[str, Any]) -> str:
    lines = [
        "# Generated by qwen35-finetuning",
        f"FROM {config['base_model']}",
        "",
    ]

    for name, value in config.get("parameters", {}).items():
        lines.append(f"PARAMETER {name} {value}")

    system_prompt = config.get("system_prompt")
    if system_prompt:
        lines.extend(["", f"SYSTEM {quote_block(system_prompt)}"])

    adapter_path = config.get("adapter_path")
    if adapter_path:
        lines.extend(["", f"ADAPTER {adapter_path}"])

    messages = config.get("messages", [])
    if messages:
        lines.append("")
    for message in messages:
        role = message["role"]
        content = str(message["content"]).replace("\n", "\\n")
        lines.append(f"MESSAGE {role} {content}")

    return "\n".join(lines).rstrip() + "\n"


def write_modelfile(config: dict[str, Any], project_root: Path) -> Path:
    output_path = project_root / config.get("output_modelfile", "ollama/Modelfile")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_modelfile(config), encoding="utf-8")
    return output_path


def create_ollama_model(model_name: str, modelfile_path: Path) -> None:
    subprocess.run(
        ["ollama", "create", model_name, "-f", str(modelfile_path)],
        check=True,
    )
